# Setup -----------------------------------------------------------------

texture.composite.depthtex2 = image/minecraftLutV2.png
texture.composite.colortex9 = image/perlinNoise.png
texture.gbuffers.colortex9 = image/perlinNoise.png
# texture.composite.colortex10 = image/perlinLowFreq.png
texture.gbuffers.colortex10 = image/perlinLowFreq.png
separateAo=true
vignette=false
clouds=off

size.buffer.colortex7 = .25 .25
size.buffer.colortex10 = .25 .25
# size.buffer.colortex8 = .25 .25


# Settings -------------------------------------------------------------

screen = <empty> <profile> <empty> [SHADOWS] [REFLECTIONS] [EFFECTS] [DEBUG]

# sliders = iScream uScream weAllScream forIceCream

screen.columns = 1
screen.SHADOWS.columns = 2
screen.REFLECTIONS.columns = 2
screen.EFFECTS.columns = 2
screen.DEBUG.columns = 2

screen.SHADOWS = SHADOW_MAPPING shadowMapResolution VARIABLE_PENUMBRA SHADOW_FILTER_SAMPLES
screen.REFLECTIONS = SSR SKY_REFLECTIONS
screen.EFFECTS = LUT LOCAL_TONE_MAPPING VIGNETTE ROUND_BLOCKS
screen.DEBUG = SHOW_DEBUG_WINDOW TONEMAPPING

# profile.LOW  = !SSAO ShadowType=1 SSR:false !program.composite2
# profile.MED  =  SSAO ShadowType=2 SSR:false !program.composite2
# profile.HIGH =  SSAO ShadowType=3 SSR:true
profile.FANCY = shadowMapResolution=4096 SHADOW_FILTER_SAMPLES=16 VARIABLE_PENUMBRA LOCAL_TONE_MAPPING LOCAL_TONE_MAPPING VIGNETTE LUT SSR SKY_REFLECTIONS !SHOW_DEBUG_WINDOW
profile.STANDARD = shadowMapResolution=2048 SHADOW_FILTER_SAMPLES=16 !VARIABLE_PENUMBRA SSR
profile.FASTER = shadowMapResolution=1024 SHADOW_FILTER_SAMPLES=8 !VARIABLE_PENUMBRA !LOCAL_TONE_MAPPING !SSR
profile.POTATO = !SHADOW_MAPPING !LOCAL_TONE_MAPPING !SSR
profile.DEBUG = SHADOW_MAPPING !LOCAL_TONE_MAPPING !VIGNETTE !LUT !SSR SHOW_DEBUG_WINDOW

program.shadowcomp.enabled=false
program.composite5.enabled=SSR

shadow.enabled=SHADOW_MAPPING # Only works on Iris
# shadowTerrain=SHADOW_MAPPING
# shadowTranslucent=SHADOW_MAPPING
# shadowEntities=SHADOW_MAPPING
# shadowPlayer=SHADOW_MAPPING