# Setup -----------------------------------------------------------------

texture.composite.depthtex2 = image/minecraftLutV2.png
texture.composite.colortex9 = image/perlinNoise.png
texture.gbuffers.colortex9 = image/perlinNoise.png
# texture.composite.colortex10 = image/perlinLowFreq.png
texture.gbuffers.colortex10 = image/perlinLowFreq.png
separateAo=true
vignette=false
clouds=off

size.buffer.colortex7 = .25 .25
size.buffer.colortex10 = .25 .25
# size.buffer.colortex8 = .25 .25


# Settings -------------------------------------------------------------

screen = <profile> <empty> [Shadows] [Reflections] [Effects] [Debug]

sliders = shadowMapResolution SHADOW_FILTER_SAMPLES MAX_SHADOW_BLUR
screen.columns = 2
screen.Shadows.columns = 2
screen.Reflections.columns = 2
screen.Effects.columns = 2
screen.Debug.columns = 2

screen.Shadows = SHADOW_MAPPING shadowMapResolution VARIABLE_PENUMBRA SHADOW_FILTER_SAMPLES MAX_SHADOW_BLUR
screen.Reflections = SSR SKY_REFLECTIONS
screen.Effects = LUT LOCAL_TONE_MAPPING VIGNETTE ROUND_BLOCKS
screen.Debug = SHOW_DEBUG_WINDOW TONEMAPPING

# profile.LOW  = !SSAO ShadowType=1 SSR:false !program.composite2
# profile.MED  =  SSAO ShadowType=2 SSR:false !program.composite2
# profile.HIGH =  SSAO ShadowType=3 SSR:true
profile.Fancy = SHADOW_MAPPING shadowMapResolution=4096 SHADOW_FILTER_SAMPLES=16 VARIABLE_PENUMBRA MAX_SHADOW_BLUR=10 LOCAL_TONE_MAPPING VIGNETTE LUT SSR SKY_REFLECTIONS !SHOW_DEBUG_WINDOW
profile.Standard = SHADOW_MAPPING shadowMapResolution=2560 SHADOW_FILTER_SAMPLES=16 !VARIABLE_PENUMBRA MAX_SHADOW_BLUR=2 SSR LOCAL_TONE_MAPPING LUT SSR SKY_REFLECTIONS
profile.Faster = SHADOW_MAPPING shadowMapResolution=1024 SHADOW_FILTER_SAMPLES=8 !VARIABLE_PENUMBRA MAX_SHADOW_BLUR=1 !LOCAL_TONE_MAPPING !SSR
profile.Potato = !SHADOW_MAPPING !LOCAL_TONE_MAPPING !SSR
profile.Debug = SHADOW_MAPPING !LOCAL_TONE_MAPPING !VIGNETTE !LUT !SSR SHOW_DEBUG_WINDOW

program.shadowcomp.enabled=false
program.composite5.enabled=SSR

shadow.enabled=SHADOW_MAPPING # Only works on Iris
# shadowTerrain=SHADOW_MAPPING
# shadowTranslucent=SHADOW_MAPPING
# shadowEntities=SHADOW_MAPPING
# shadowPlayer=SHADOW_MAPPING